### ISSUE TITLE
iOS 13 compatibility 

### ISSUE THREAD

**Issue by ahanank** [gilshahar7/ExactTime#3]
Hi there, would there be an update for iOS 13 in the near future? I tested it recently on iOS 13 and just letting you know, it doesn’t work. Didn’t see an issue posted so thought I should report :)

**Comment by gilshahar7** [comment]
Thanks for reaching out, i do have a jailbroken device running iOS 13 and i
have noticed that ExactTime is not working. I am planning on updating it
but i dont have the time for it right now because of studies.

The code is open sourced and if there is anyone who can make a pull request
to fix this, ill be more than happy to accept it and push the update to
Packix.

I suspect that the change that is required is simply a class name change.

**Comment by ahanank** [comment]
> Thanks for reaching out, i do have a jailbroken device running iOS 13 and i have noticed that ExactTime is not working. I am planning on updating it but i dont have the time for it right now because of studies. The code is open sourced and if there is anyone who can make a pull request to fix this, ill be more than happy to accept it and push the update to Packix. I suspect that the change that is required is simply a class name change.
> […](#)

No problem at all, at your convenience then.

**Comment by gilshahar7** [comment]
Hey, i just updated the tweak to work on iOS 13. the deb file is also available until Packix approves this version.

Basically it was a stupid fix, i forgot that i restricted the tweak from loading on iOS versions higher than iOS 12. so i just removed that and it's all good now.

**Comment by ahanank** [comment]
Thank you so much! You are awesome.
